#!/usr/bin/env python3
"""Regenerate compile_project.py: a single-file materializer of this project.

Run this any time src/, tests/, config/, docs/, or the top-level project
files change, and commit the regenerated output alongside your edit.

    python3 tools/build_single_file.py

The output is a plain Python script with **no dependencies of its own**
(stdlib only): running it with `python3 compile_project.py [target_dir]`
writes out the project tree with canonical LF text line endings. Binary
fixtures are preserved byte-for-byte. This exists for two
reasons: a single file is easy to paste into an environment that can't clone
a git repo, and it makes tampering obvious -- the file's own embedded
manifest hash is checked at materialization time, so a corrupted or
hand-edited copy refuses to run rather than writing out something subtly
different from what was built here.

This script deliberately does NOT try to be the source of truth. src/ is the
source of truth; this is a build artifact of it, the same way a wheel is a
build artifact of a package. Never hand-edit compile_project.py.
"""

from __future__ import annotations

import base64
import hashlib
import lzma
import sys
from datetime import UTC
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = REPO_ROOT / "compile_project.py"

# What ships in the single file. Deliberately excludes anything gitignored
# (the SQLite database, .env, caches) and anything that is itself a build
# artifact (this tool's own output).
INCLUDE_GLOBS = [
    "src/**/*.py",
    "tools/*.py",
    "src/predoc_pipeline/py.typed",
    "tests/**/*.py",
    "tests/fixtures/*.jsonl",
    "tests/fixtures/boards/**/*",
    "config/*.toml",
    "docs/index.html",
    "docs/data/*.json",
    "docs/feed.xml",
    ".github/workflows/*.yml",
    ".github/dependabot.yml",
    "pyproject.toml",
    "uv.lock",
    "review/**/*.md",
    "review/**/*.json",
    "review/**/*.py",
    ".gitignore",
    ".gitattributes",
    ".env.example",
    "Makefile",
    "LICENSE",
    "README.md",
    "ARCHITECTURE.md",
    "REVIEW.md",
    "COMPLIANCE.md",
    "OPERATIONS.md",
    "CHANGES.md",
    "FINALIZATION.md",
    "docs/X_THREAD_RECOVERY.md",
    "SETUP_GUIDE.md",
]

EXCLUDE_SUFFIXES = (".pyc", ".pyo")
EXCLUDE_DIR_PARTS = {"__pycache__", ".git", ".pytest_cache", ".mypy_cache", ".ruff_cache"}
TEXT_SUFFIXES = {
    '.py', '.toml', '.md', '.yml', '.html', '.json', '.xml', '.jsonl', '.lock', '.example',
}
TEXT_NAMES = {'Makefile', '.gitignore', '.gitattributes'}


def collect_files() -> list[Path]:
    seen: set[Path] = set()
    files: list[Path] = []
    for pattern in INCLUDE_GLOBS:
        for path in sorted(REPO_ROOT.glob(pattern)):
            if not path.is_file():
                continue
            if path.suffix in EXCLUDE_SUFFIXES:
                continue
            if EXCLUDE_DIR_PARTS & set(path.relative_to(REPO_ROOT).parts):
                continue
            if path == OUTPUT_PATH:
                continue
            if path not in seen:
                seen.add(path)
                files.append(path)
    return files


def build_manifest(files: list[Path]) -> tuple[dict[str, bytes], str]:
    """Build the {path: bytes} payload and its manifest hash.

    The hash MUST be computed by iterating paths in sorted order: the
    generated materializer's own `_verify` sorts before hashing (so it does
    not depend on dict insertion order at unpack time), so building the
    reference hash in any other order here would make every materialization
    fail its own integrity check.
    """
    payload: dict[str, bytes] = {}
    for path in files:
        rel = path.relative_to(REPO_ROOT).as_posix()
        content = path.read_bytes()
        # Git may check out text as CRLF on Windows and LF in Linux CI. Encode
        # the same distribution from both checkouts without touching binaries.
        if path.suffix in TEXT_SUFFIXES or path.name in TEXT_NAMES:
            content = content.replace(b'\r\n', b'\n')
        payload[rel] = content

    hasher = hashlib.sha256()
    for rel in sorted(payload):
        hasher.update(rel.encode("utf-8"))
        hasher.update(hashlib.sha256(payload[rel]).digest())
    return payload, hasher.hexdigest()


MATERIALIZER_TEMPLATE = '''#!/usr/bin/env python3
"""Auto-generated by tools/build_single_file.py. DO NOT EDIT BY HAND.

This file is a single-file materializer for the predoc-pipeline project.
Running it writes out the full source tree (src/, tests/, config/, docs/,
workflows, and project files) into a target directory using only the
standard library -- no dependencies are required to unpack it.

Usage:
    python3 compile_project.py [target_dir]     # default target_dir: ./predoc-pipeline

After materializing, follow README.md: create a virtualenv, install with
`pip install -e ".[portals]"`, copy .env.example to .env, and read
COMPLIANCE.md before enabling any optional source.

Build info:
    generated_at   = {generated_at!r}
    file_count     = {file_count}
    manifest_sha256 = {manifest_hash!r}
"""

from __future__ import annotations

import base64
import hashlib
import lzma
import sys
from pathlib import Path

MANIFEST_SHA256 = {manifest_hash!r}

_PAYLOAD_B64 = """
{payload_b64}
"""


def _unpack() -> dict[str, bytes]:
    compressed = base64.b64decode(_PAYLOAD_B64.encode("ascii"))
    raw = lzma.decompress(compressed)
    files: dict[str, bytes] = {{}}
    pos = 0
    while pos < len(raw):
        nl = raw.index(b"\\n", pos)
        header = raw[pos:nl].decode("utf-8")
        rel_path, size_str = header.rsplit("\\t", 1)
        size = int(size_str)
        start = nl + 1
        files[rel_path] = raw[start:start + size]
        pos = start + size
    return files


def _verify(files: dict[str, bytes]) -> None:
    hasher = hashlib.sha256()
    for rel_path in sorted(files):
        hasher.update(rel_path.encode("utf-8"))
        hasher.update(hashlib.sha256(files[rel_path]).digest())
    digest = hasher.hexdigest()
    if digest != MANIFEST_SHA256:
        print(
            f"error: manifest mismatch (expected {{MANIFEST_SHA256}}, got {{digest}}).\\n"
            "This file may have been edited or corrupted. Refusing to materialize.",
            file=sys.stderr,
        )
        sys.exit(1)


def main() -> None:
    target = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("predoc-pipeline")
    files = _unpack()
    _verify(files)

    if target.exists() and any(target.iterdir()):
        answer = input(f"{{target}} exists and is not empty. Continue? [y/N] ")
        if answer.strip().lower() != "y":
            print("aborted")
            sys.exit(1)

    for rel_path, data in files.items():
        out = target / rel_path
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_bytes(data)

    print(f"materialized {{len(files)}} files into {{target}}/")
    print("next: cd", target, "&& python3 -m venv .venv && . .venv/bin/activate && "
          "pip install -e \\".[portals]\\" && cp .env.example .env")


if __name__ == "__main__":
    main()
'''


def main() -> None:
    files = collect_files()
    if not files:
        print("no files matched INCLUDE_GLOBS; nothing to do", file=sys.stderr)
        sys.exit(1)

    payload, manifest_hash = build_manifest(files)

    raw = bytearray()
    for rel_path in sorted(payload):
        data = payload[rel_path]
        header = f"{rel_path}\t{len(data)}\n".encode()
        raw += header
        raw += data

    compressed = lzma.compress(bytes(raw), preset=9)
    payload_b64 = base64.b64encode(compressed).decode("ascii")
    wrapped = "\n".join(payload_b64[i : i + 100] for i in range(0, len(payload_b64), 100))

    from datetime import datetime

    output = MATERIALIZER_TEMPLATE.format(
        generated_at=datetime.now(UTC).isoformat(),
        file_count=len(files),
        manifest_hash=manifest_hash,
        payload_b64=wrapped,
    )
    OUTPUT_PATH.write_text(output, encoding="utf-8")
    print(f"wrote {OUTPUT_PATH} ({len(files)} files packed, manifest {manifest_hash[:12]}...)")


if __name__ == "__main__":
    main()
